#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_martyn="0.0.1"
  jq -n --arg martyn "$ver_martyn" '{martyn: $martyn}'
}

version "$@"
